### ISSUE TITLE
automate EDF text file extraction 

### ISSUE THREAD

**Issue by angelaradulescu** [nivlab/NivLink#2]

**Comment by angelaradulescu** [comment]
Further tested pyedfread, and the sample extraction seemed not to work properly. Also, the output was not quite what we need. We're looking for the equivalent to the "Sample report" which DataViewer generates, i.e. a text file with row of data for every sample recorded by the eye-tracker during the study.

**Comment by szorowi1** [comment]
Gonna open this back up. Between [pyedfread](https://github.com/nwilming/pyedfread/tree/master/pyedfread) and [pyparse](https://github.com/pyeparse/pyeparse/tree/master/pyeparse/edf) I think I have the skeleton to write something flexible and efficient. No promises but will try to have a solution ASAP.

**Comment by szorowi1** [comment]
Update: v0.2 of NivLink will support direct EDF reading. For an early working version, see the v0.2 branch.
