### ISSUE TITLE
Test workflow with manually generating full "Sample reports" from DataViewer 

### ISSUE THREAD

**Issue by angelaradulescu** [nivlab/NivLink#5]
Previously, manual extraction of sample reports from Data Viewer required remembering which variables we want to put in the report. Can we switch to generating a full report and indexing by column name rather than number?

**Comment by angelaradulescu** [comment]
Tested this and it works fine! Next up: include in workflow tests using some sample raw data.

**Comment by szorowi1** [comment]
Can this be closed then?
