### ISSUE TITLE
Allow epoching function to handle multiple screens (pass screen index in events file)

### ISSUE THREAD

**Issue by angelaradulescu** [nivlab/NivLink#9]
Came up when thinking about how to analyze MOAT, which has different AoIs on each trial (4 possible cases).

**Comment by szorowi1** [comment]
This is a fun indexing problem haha. I think it can be handled with 3 changes to `align_to_aoi`.

1. The function itself should accept three arguments, `align_to_aoi(epochs, info, indices)`, where *info* can be a single or list of `ScreenInfo` instances and *indices* is a shape = *(n_trial, 1)* vector assigning each trial in *epochs* to an info object.
2. Some additional error handling should be written to preempt any likely user error (e.g.  *info* is a list not comprised entirely of`ScreenInfo` instances; *indices* has more unique trials than `ScreenInfo` instances in *info*).
3. A for loop performing eyefix-to-AoI mapping for each ScreenInfo object. This will require updating indexing to reflect both trials corresponding to the ScreenInfo object and missing data.

I think you mentioned wanting to take this on, so I'll leave it to you. Let me know if there's anything I can do!

**Comment by angelaradulescu** [comment]
Resolved in [13](https://github.com/nivlab/NivLink/pull/13).
